### ISSUE TITLE
设备ID不存在，需要二次设备校验

### ISSUE THREAD

**Issue by jarryyen** [Ysnsn/cloud189-sign#1]
你好,目前遇到了一个问题.
设备ID不存在，需要二次设备校验
似乎官方做了限制

**Comment by Ysnsn** [comment]
不知道，没遇到过

**Comment by jarryyen** [comment]
....不知道是怎么回事了....

**Comment by jarryyen** [comment]
我刚刚在action中跑了一遍,您可以去看日志

**Comment by Ysnsn** [comment]
账号密码填对了吗？自己手再动登录看看能不能签到

**Comment by jarryyen** [comment]
已经解决了,谢谢.
修改一下密码就可以了,好像是触发了防控.
